apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-wffc-retain
provisioner: cinder.csi.openstack.org
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
