apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkyboard-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/LinkyBoard/linkyboard-k8s.git'
    targetRevision: main
    path: postgres-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: linkyboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
